### ISSUE TITLE
MiniMe pet.

### ISSUE THREAD

**Issue by nightfire187** [danielntech/miniaturepets#1]
When trying to spawn minime pet. i get this in the console. I have tried replacing minime and reinstalling the plugin but still the same thing. It worked fine for a few weeks then this started. I was able to fix it by deleting the data folder but not anymore.

`[19:49:58] [Server thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@2336083c[id=df7b55ef-ff44-4d52-b7cd-c798df1aecf1,name=nightfire187,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:79) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$1.load(TileEntitySkull.java:1) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:206) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.TileEntitySkull$3.call(TileEntitySkull.java:1) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at net.minecraft.server.v1_12_R1.TileEntitySkull.b(TileEntitySkull.java:222) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftMetaSkull.applyToItem(CraftMetaSkull.java:81) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.setItemMeta(CraftItemStack.java:431) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.asNMSCopy(CraftItemStack.java:45) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftEntityEquipment.setEquipment(CraftEntityEquipment.java:103) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftEntityEquipment.setHelmet(CraftEntityEquipment.java:54) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftArmorStand.setHelmet(CraftArmorStand.java:79) [Spigot.jar:git-Spigot-4bd94dc-fd702e4]
	at com.kirelcodes.miniaturepets.`

**Comment by danielntech** [comment]
I'll have this investigated, please hold on as we are checking the matter. It might take some time.

**Comment by NacOJerk** [comment]
Please add a /mpet dump log

**Comment by nightfire187** [comment]
User ID: 12164
Nonce : 1194271902
Version : v1_12_R1
Platform : Spigot
Plugins:
 * AsyncWorldEditInjector version 3.5.2
 * LuckPerms version 4.1.25
 * nightsevents version 0.1
 * PlaceholderAPI version 2.8.6
 * WorldBorder version 1.8.7
 * Discord version 1.3
 * Votifier version 1.9
 * Multiverse-Core version 2.5-b719
 * ProtocolLib version 4.3.0
 * NoCheatPlus version 3.16.0-RC-sMD5NET-b1134
 * EditDrops version 1.0.6
 * OpenTerrainGenerator version 1.12.2 v4
 * ChatColorPlus version 2.6.5
 * AdvancedPortals version 0.0.39
 * AsyncWorldEdit version 3.5.2
 * Vouchers version 1.6.5.3
 * iDisguise version 5.6.4
 * RandomTeleport version 2.3
 * ServerListPlus version 3.4.8
 * Vault version 1.5.6-b49
 * SimpleSit version 1.6.3
 * Emojis version 1.0
 * WorldEdit version 6.1.8-SNAPSHOT;cd4729f
 * Essentials version 2.0.1-b612
 * Parties version 2.2.18
 * EpicRename version 3.3.1
 * HeadDatabase version 4.3.2
 * HolographicDisplays version 2.2.6
 * LWC version 2.0.5
 * CrateReloaded version 1.3.98.3
 * CommandSigns version 1.6.3
 * LPMessenger version 0.5-BETA
 * WorldGuard version 6.2.1;84bc322
 * AdvancedAchievements version 5.7.2
 * EssentialsChat version 2.0.1-b612
 * SurvivalPlots version 1.0.5
 * SuperbVote version 0.4.1
 * EssentialsSpawn version 2.0.1-b612
 * AntiCombatLogging version 4.8.0
 * EnjinMinecraftPlugin version 3.4.3
 * MiniaturePets version 1.5.4
 * Jobs version 4.5.3
 * SilkSpawners version 3.0 ALPHA 1

**Comment by danielntech** [comment]
Thank you, your dump log was registered :)

**Comment by scarabcoder** [comment]
That doesn't look like a full error log (cut off at the bottom).
It would seem, though, you're trying to download too many skins onto a skull and Mojang is blocking the requests due to their (fairly low) rate limit.

**Comment by nightfire187** [comment]
No the server is not cracked.

And I almost 100% sure that was the full error. But I'll look again in a few days, I'm on vacation atm.

**Comment by danielntech** [comment]
Thank you both, I'll send both comments to our developer for checking again.

**Comment by danielntech** [comment]
I appreciate your wait, it took us a while. In 2.0 this will be resolved. 

Have a great day!
