### ISSUE TITLE
Bug pet name

### ISSUE THREAD

**Issue by Leoodiaz10** [danielntech/miniaturepets#12]
https://i.imgur.com/bWaHtGz.png

**Comment by danielntech** [comment]
I am not confident this is an issue, I'll verify this, but I'm pretty confident it is at your side.

**Comment by Leoodiaz10** [comment]
I have tried the plugin in a local server, with only that plugin, without any more and with Spigot 1.8.8 and I still see that same error

**Comment by Leoodiaz10** [comment]
Error in console

 at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??.?(AnimationCycle.java:92) ~[?:?]
        at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??.<init>(AnimationCycle.java:76) ~[?:?]
        at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??.?(PetContainer.java:196) ~[?:?]
        at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??.?(PetContainer.java:183) ~[?:?]
        at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??.?(PetContainer.java:177) ~[?:?]
        at com.kirelcodes.miniaturepets. .????????????????????????????????????????????????????????????????????????????????????????????????????.??$2.run(CoreListener.java:495) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by danielntech** [comment]
You've never mentioned any error in the console.
Please attach a full description to this bug report.

Guidance:
Short description:
Long description:
Actions to repeat / ways of reaching the bug:
MPets Dump Link:

Small note: It was asked a lot frequently, the MPets Dump Link: field refers to the dump link that is obtained from running the command **/mpet dump** in-game. Paste the link it gives you inside the field.
