### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by 100petr** [danielntech/miniaturepets#27]
I found in console this error:
`[19:07:50 WARN]: [MiniaturePets] Task #213788 for MiniaturePets v1.5.71 generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between world and Spawn
at org.bukkit.Location.distanceSquared(Location.java:460) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at com.kirelcodes.miniaturepets..??ע???????????????????????????????????????????י?????????????????????ט??????????ו??ץ??א??????????????.ךך$2.run(BasicPet.java:271) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [minecraft_server.jar:git-Spigot-2cf50f0-2b93d83]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]`

**Comment by danielntech** [comment]
What version of Spigot are you running?

**Comment by NacOJerk** [comment]
Also please update to the latest version

**Comment by danielntech** [comment]
This has been closed due to inactivity.
