### ISSUE TITLE
Plugin conflicts - Miniaturepets with mythicmobs

### ISSUE THREAD

**Issue by ChristyGrnKnght** [danielntech/miniaturepets#44]
When I have miniature pets on my server it prevents mythicmobs from working. Deleting miniaturepets allows mythicmobs to work, but I don't want to have to delete miniaturepets.  The error message is here:

[19:31:58] [Server thread/ERROR]: Error occurred while enabling MythicMobs v4.4.0
java.lang.NoClassDefFoundError: com/kirelcodes/miniaturepets/api/pets/APIMobContainer
	at io.lumine.xikage.mythicmobs.compatibility.MPetCompat$MiniaturePetType.<init>(MPetCompat.java:47) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MythicMob.<init>(MythicMob.java:219) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.loadMobs(MobManager.java:104) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.io.ConfigManager.LoadAll(ConfigManager.java:93) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.MythicMobs.onEnable(MythicMobs.java:142) ~[MythicMobs-4.4.0%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.ClassNotFoundException: com.kirelcodes.miniaturepets.api.pets.APIMobContainer
	at java.net.URLClassLoader[19:31:58] [Server thread/ERROR]: Error occurred while enabling MythicMobs v4.4.0 (Is it up to date?)
java.lang.NoClassDefFoundError: com/kirelcodes/miniaturepets/api/pets/APIMobContainer
	at io.lumine.xikage.mythicmobs.compatibility.MPetCompat$MiniaturePetType.<init>(MPetCompat.java:47) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MythicMob.<init>(MythicMob.java:219) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.loadMobs(MobManager.java:104) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.io.ConfigManager.LoadAll(ConfigManager.java:93) ~[MythicMobs-4.4.0%20(1).jar:?]
	at io.lumine.xikage.mythicmobs.MythicMobs.onEnable(MythicMobs.java:142) ~[MythicMobs-4.4.0%20(1).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:427) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:341) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:582) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:545) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:423) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:288) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_65]
Caused by: java.lang.ClassNotFoundException: com.kirelcodes.miniaturepets.api.pets.APIMobContainer
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65].findClass(Unknown Source) ~[?:1.8.0_65]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[custom.jar:git-Spigot-0ede7d0-c88ae6b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_65]

**Comment by SirBailey** [comment]
MiniaturePets used to hook into MythicMobs but since 2.0 it doesn't support it. NacOJerk will be adding back MythicMobs support soon.

**Comment by danielntech** [comment]
Couldn't say it better then Bailey, in the near future we will readd support on our side, the rest entirely depends on the Mythic Mobs developer.
